//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO2022.ASP.Net.Lab03.Ex01to02.RSVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestResponses
    {
        public GuestResponses()
        {
            this.Reports = new HashSet<Reports>();
        }
    
        public int GuestResponseId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> WillAttend { get; set; }
        public System.DateTime Rdata { get; set; }
    
        public virtual ICollection<Reports> Reports { get; set; }
    }
}
