//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO2022.ASP.Net.Lab03.Ex01to02.RSVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int ReportId { get; set; }
        public string NameReport { get; set; }
        public string Annotation { get; set; }
        public Nullable<int> GuestRes_GuestResponseId { get; set; }
    
        public virtual GuestResponses GuestResponses { get; set; }
    }
}
